# Conclusion

The main objective of this project was to analyze and visualize the various factors which have contributed to the Evolution of Olympic Games over the years. Based on the analysis, we get these key interesting insights: 

1) The number of athletes, Teams and Sports of Summer and Winter Olympics has grown significantly since 1896, and reached a saturation point during the 2000s. 

2) The female participation increases significantly and gender equality is a top priority for the Olympic Movement. 

3) The development of the countries affected the number of medals won, developed countries are more possible to win the medal. 

4) The age of the athletes is not correlated to the medal win, but the weight and height have a specific relationship with the race results.

Since we only performed Exploratory Data Analysis in this project,  there exists some limitations which need a further scope of this project: we can build a predictive model by Machine Learning and Deep Learning Algorithms, which can predict the statistics of Future Olympics.
